import Sidebar from "@/layouts/components/sidebar";
import "@/styles/global.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div id="" className="h-fit block md:flex">
          <Sidebar />
          <main className="flex-1 flex-grow w-full min-h-fit overflow-hidden">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
